// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/proto/expression/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_PLUS  Operation = 0
	Operation_MINUS Operation = 1
	Operation_MULTI Operation = 2
	Operation_DIV   Operation = 3
	Operation_MOD   Operation = 4
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "PLUS",
		1: "MINUS",
		2: "MULTI",
		3: "DIV",
		4: "MOD",
	}
	Operation_value = map[string]int32{
		"PLUS":  0,
		"MINUS": 1,
		"MULTI": 2,
		"DIV":   3,
		"MOD":   4,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_expression_event_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_api_proto_expression_event_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_expression_event_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lhs       int64     `protobuf:"varint,1,opt,name=lhs,proto3" json:"lhs,omitempty"`
	Rhs       int64     `protobuf:"varint,2,opt,name=rhs,proto3" json:"rhs,omitempty"`
	Operation Operation `protobuf:"varint,3,opt,name=operation,proto3,enum=expression.Operation" json:"operation,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_expression_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_expression_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_expression_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetLhs() int64 {
	if x != nil {
		return x.Lhs
	}
	return 0
}

func (x *Event) GetRhs() int64 {
	if x != nil {
		return x.Rhs
	}
	return 0
}

func (x *Event) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_PLUS
}

var File_api_proto_expression_event_proto protoreflect.FileDescriptor

var file_api_proto_expression_event_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x60,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x68, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x68, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x68, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x68, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2a, 0x3d, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x49, 0x4e, 0x55, 0x53,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x44, 0x49, 0x56, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4f, 0x44, 0x10, 0x04, 0x42,
	0x21, 0x5a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_expression_event_proto_rawDescOnce sync.Once
	file_api_proto_expression_event_proto_rawDescData = file_api_proto_expression_event_proto_rawDesc
)

func file_api_proto_expression_event_proto_rawDescGZIP() []byte {
	file_api_proto_expression_event_proto_rawDescOnce.Do(func() {
		file_api_proto_expression_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_expression_event_proto_rawDescData)
	})
	return file_api_proto_expression_event_proto_rawDescData
}

var file_api_proto_expression_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_expression_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_expression_event_proto_goTypes = []interface{}{
	(Operation)(0), // 0: expression.Operation
	(*Event)(nil),  // 1: expression.Event
}
var file_api_proto_expression_event_proto_depIdxs = []int32{
	0, // 0: expression.Event.operation:type_name -> expression.Operation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_expression_event_proto_init() }
func file_api_proto_expression_event_proto_init() {
	if File_api_proto_expression_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_expression_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_expression_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_expression_event_proto_goTypes,
		DependencyIndexes: file_api_proto_expression_event_proto_depIdxs,
		EnumInfos:         file_api_proto_expression_event_proto_enumTypes,
		MessageInfos:      file_api_proto_expression_event_proto_msgTypes,
	}.Build()
	File_api_proto_expression_event_proto = out.File
	file_api_proto_expression_event_proto_rawDesc = nil
	file_api_proto_expression_event_proto_goTypes = nil
	file_api_proto_expression_event_proto_depIdxs = nil
}
