// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/proto/grpc/calculator/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression []string `protobuf:"bytes,1,rep,name=expression,proto3" json:"expression,omitempty"`
}

func (x *CalculatorRequest) Reset() {
	*x = CalculatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_grpc_calculator_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorRequest) ProtoMessage() {}

func (x *CalculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_calculator_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorRequest.ProtoReflect.Descriptor instead.
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_calculator_service_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatorRequest) GetExpression() []string {
	if x != nil {
		return x.Expression
	}
	return nil
}

type CalculatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculatorReply) Reset() {
	*x = CalculatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_grpc_calculator_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorReply) ProtoMessage() {}

func (x *CalculatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_calculator_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorReply.ProtoReflect.Descriptor instead.
func (*CalculatorReply) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_calculator_service_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatorReply) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_proto_grpc_calculator_service_proto protoreflect.FileDescriptor

var file_api_proto_grpc_calculator_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x29, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x68, 0x0a, 0x11, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x53, 0x0a, 0x0b, 0x44, 0x6f, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x22,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x28, 0x5a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_grpc_calculator_service_proto_rawDescOnce sync.Once
	file_api_proto_grpc_calculator_service_proto_rawDescData = file_api_proto_grpc_calculator_service_proto_rawDesc
)

func file_api_proto_grpc_calculator_service_proto_rawDescGZIP() []byte {
	file_api_proto_grpc_calculator_service_proto_rawDescOnce.Do(func() {
		file_api_proto_grpc_calculator_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_grpc_calculator_service_proto_rawDescData)
	})
	return file_api_proto_grpc_calculator_service_proto_rawDescData
}

var file_api_proto_grpc_calculator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_grpc_calculator_service_proto_goTypes = []interface{}{
	(*CalculatorRequest)(nil), // 0: grpc.calculator.CalculatorRequest
	(*CalculatorReply)(nil),   // 1: grpc.calculator.CalculatorReply
}
var file_api_proto_grpc_calculator_service_proto_depIdxs = []int32{
	0, // 0: grpc.calculator.CalculatorService.DoCalculate:input_type -> grpc.calculator.CalculatorRequest
	1, // 1: grpc.calculator.CalculatorService.DoCalculate:output_type -> grpc.calculator.CalculatorReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_grpc_calculator_service_proto_init() }
func file_api_proto_grpc_calculator_service_proto_init() {
	if File_api_proto_grpc_calculator_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_grpc_calculator_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_grpc_calculator_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_grpc_calculator_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_grpc_calculator_service_proto_goTypes,
		DependencyIndexes: file_api_proto_grpc_calculator_service_proto_depIdxs,
		MessageInfos:      file_api_proto_grpc_calculator_service_proto_msgTypes,
	}.Build()
	File_api_proto_grpc_calculator_service_proto = out.File
	file_api_proto_grpc_calculator_service_proto_rawDesc = nil
	file_api_proto_grpc_calculator_service_proto_goTypes = nil
	file_api_proto_grpc_calculator_service_proto_depIdxs = nil
}
